/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/2026-bugatti-tourbillon-4f63f5a74611477989cefd9861b9784a
Title: 2026 Bugatti Tourbillon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Buggati(props) {
  const { nodes, materials } = useGLTF('https://gaapupgzgvpsestztgyn.supabase.co/storage/v1/object/sign/car-models/BuggatiTourbillonNewC.glb?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJjYXItbW9kZWxzL0J1Z2dhdGlUb3VyYmlsbG9uTmV3Qy5nbGIiLCJpYXQiOjE3NDQ5MjM3OTQsImV4cCI6MjA2MDI4Mzc5NH0.msG5OKLa4_zkFmXJGP8Ai9DyB0gHwTVclFaos99HfLs')
  return (
    <group {...props} dispose={null} scale={100} position={[0.2,-1,-0.6]} rotation={[0,5.3,0]}>
      <group scale={0.01}>
        <primitive object={nodes._rootJoint} />
        <group position={[0, 0.104, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes
                .bInterior_Geo_lodA_Interior_Geo_lodA_Bugatti_Tourbillon_2026InteriorA_Material_bBugatti_Tourbillon_2026InteriorA_Material1_0
                .geometry
            }
            material={materials.bBugatti_Tourbillon_2026InteriorA_Material1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes
                .bInterior_Geo_lodA_Interior_Geo_lodA_Bugatti_Tourbillon_2026InteriorA_Material_bBugatti_Tourbillon_2026InteriorA_Material1_0_1
                .geometry
            }
            material={materials.bBugatti_Tourbillon_2026InteriorA_Material1}
          />
        </group>
        <group position={[0, 0.104, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes
                .bPaint_Geo_lodA_Paint_Geo_lodA_Bugatti_Tourbillon_2026Paint_Material_bBugatti_Tourbillon_2026Paint_Material1_0
                .geometry
            }
            material={materials.bBugatti_Tourbillon_2026Paint_Material1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.bPaint_Geo_lodA_Paint_Geo_lodA_Bugatti_Tourbillon_2026Paint_Material_col_2_0
                .geometry
            }
            material={materials.col_2}
          />
        </group>
        <group position={[0, 0.104, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes
                .bWindow_Geo_lodA_Window_Geo_lodA_Bugatti_Tourbillon_2026Window_Material_bBugatti_Tourbillon_2026Window_Material1_0
                .geometry
            }
            material={materials.bBugatti_Tourbillon_2026Window_Material1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes
                .bWindow_Geo_lodA_Window_Geo_lodA_Bugatti_Tourbillon_2026Window_Material_red_glass_0
                .geometry
            }
            material={materials.red_glass}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bBadge_Geo_lodA_Badge_Geo_lodA_Bugatti_Tourbillon_2026BadgeA_Material_bBugatti_Tourbillon_2026BadgeA_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026BadgeA_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bBase_Geo_lodA_Base_Geo_lodA_Bugatti_Tourbillon_2026Base_Material_bBugatti_Tourbillon_2026Base_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026Base_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bCarbon1_Geo_lodA_Carbon1_Geo_lodA_Bugatti_Tourbillon_2026Carbon1_Material_bBugatti_Tourbillon_2026Carbon1_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026Carbon1_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bColoured_Geo_lodA_Coloured_Geo_lodA_Bugatti_Tourbillon_2026Coloured_Material_bBugatti_Tourbillon_2026Coloured_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026Coloured_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bEngine_Geo_lodA_Engine_Geo_lodA_Bugatti_Tourbillon_2026EngineA_Material_bBugatti_Tourbillon_2026EngineA_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026EngineA_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bGrilleAlpha1_Geo_lodA_GrilleAlpha1_Geo_lodA_Bugatti_Tourbillon_2026GrilleAlpha1A_Material_bBugatti_Tourbillon_2026GrilleAlpha1A_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026GrilleAlpha1A_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bGrilleAlpha2_Geo_lodA_GrilleAlpha2_Geo_lodA_Bugatti_Tourbillon_2026GrilleAlpha2A_Material_bBugatti_Tourbillon_2026GrilleAlpha2A_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026GrilleAlpha2A_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bGrilleAlpha4_Geo_lodA_GrilleAlpha4_Geo_lodA_Bugatti_Tourbillon_2026GrilleAlpha4A_Material_bBugatti_Tourbillon_2026GrilleAlpha4A_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026GrilleAlpha4A_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bGrilleNoAlpha3_Geo_lodA_GrilleNoAlpha3_Geo_lodA_Bugatti_Tourbillon_2026GrilleNoAlpha3A_Material_bBugatti_Tourbillon_2026GrilleNoAlpha3A_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026GrilleNoAlpha3A_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bGrilleNoAlpha5_Geo_lodA_GrilleNoAlpha5_Geo_lodA_Bugatti_Tourbillon_2026GrilleNoAlpha5A_Material_bBugatti_Tourbillon_2026GrilleNoAlpha5A_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026GrilleNoAlpha5A_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bGrilleNoAlpha6_Geo_lodA_GrilleNoAlpha6_Geo_lodA_Bugatti_Tourbillon_2026GrilleNoAlpha6A_Material_bBugatti_Tourbillon_2026GrilleNoAlpha6A_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026GrilleNoAlpha6A_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bGrilleNoAlpha7_Geo_lodA_GrilleNoAlpha7_Geo_lodA_Bugatti_Tourbillon_2026GrilleNoAlpha7A_Material_bBugatti_Tourbillon_2026GrilleNoAlpha7A_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026GrilleNoAlpha7A_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bGrilleNoAlpha8_Geo_lodA_GrilleNoAlpha8_Geo_lodA_Bugatti_Tourbillon_2026GrilleNoAlpha8A_Material_bBugatti_Tourbillon_2026GrilleNoAlpha8A_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026GrilleNoAlpha8A_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bInteriorColourZone_Geo_lodA_InteriorColourZone_Geo_lodA_Bugatti_Tourbillon_2026InteriorColourZoneA_Material_bBugatti_Tourbillon_2026InteriorColourZoneA_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026InteriorColourZoneA_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bInteriorTillingColourZone_Geo_lodA_InteriorTillingColourZone_Geo_lodA_Bugatti_Tourbillon_2026InteriorTillingColourZoneA_Material_bBugatti_Tourbillon_2026InteriorTillingColourZoneA_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026InteriorTillingColourZoneA_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bLight_Geo_lodA_Light_Geo_lodA_Bugatti_Tourbillon_2026LightA_Material_bBugatti_Tourbillon_2026LightA_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026LightA_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bManufacturerPlate_Geo_lodA_ManufacturerPlate_Geo_lodA_Bugatti_Tourbillon_2026ManufacturerPlateA_Material_bBugatti_Tourbillon_2026ManufacturerPlateA_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026ManufacturerPlateA_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bSeatBelt_Geo_lodA_SeatBelt_Geo_lodA_Bugatti_Tourbillon_2026SeatBelt_Material_bBugatti_Tourbillon_2026Coloured_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026Coloured_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bTextured_Geo_lodA_Textured_Geo_lodA_Bugatti_Tourbillon_2026TexturedA_Material_bBugatti_Tourbillon_2026TexturedA_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026TexturedA_Material1}
          position={[0, 0.104, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes
              .bWindowInside_Geo_lodA_WindowInside_Geo_lodA_Bugatti_Tourbillon_2026WindowInside_Material_bBugatti_Tourbillon_2026Window_Material1_0
              .geometry
          }
          material={materials.bBugatti_Tourbillon_2026Window_Material1}
          position={[0, 0.104, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('https://gaapupgzgvpsestztgyn.supabase.co/storage/v1/object/sign/car-models/BuggatiTourbillonNewC.glb?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJjYXItbW9kZWxzL0J1Z2dhdGlUb3VyYmlsbG9uTmV3Qy5nbGIiLCJpYXQiOjE3NDQ5MjM3OTQsImV4cCI6MjA2MDI4Mzc5NH0.msG5OKLa4_zkFmXJGP8Ai9DyB0gHwTVclFaos99HfLs')


