/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2019-lamborghini-huracan-evo-089c0f05bd76412e96f94a121f6dcec7
Title: 2019 Lamborghini Huracan Evo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LamboHuracanEvo(props) {
  const { nodes, materials } = useGLTF('https://gaapupgzgvpsestztgyn.supabase.co/storage/v1/object/sign/car-models/LamborghiniHuracanEvoC.glb?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJjYXItbW9kZWxzL0xhbWJvcmdoaW5pSHVyYWNhbkV2b0MuZ2xiIiwiaWF0IjoxNzQ0OTE0NzY1LCJleHAiOjIwNjAyNzQ3NjV9.moqF5FPQynYFeNzhna5E3CEZ0J4rhX2wis5j-5fu8cU')
  return (
    <group {...props} dispose={null} scale={.01} position={[0.2,-1,-0.6]} rotation={[0,5.3,0]}>
      <primitive object={nodes._rootJoint} />
    </group>
  )
}

useGLTF.preload('https://gaapupgzgvpsestztgyn.supabase.co/storage/v1/object/sign/car-models/LamborghiniHuracanEvoC.glb?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJjYXItbW9kZWxzL0xhbWJvcmdoaW5pSHVyYWNhbkV2b0MuZ2xiIiwiaWF0IjoxNzQ0OTE0NzY1LCJleHAiOjIwNjAyNzQ3NjV9.moqF5FPQynYFeNzhna5E3CEZ0J4rhX2wis5j-5fu8cU')
